language: python
branches:
  only:
  - master
install:
- pip install pelican
- pip install ghp-import
- pip install pelican_gist
script:
- make publish github
env:
  global:
  - secure: fh/g/6XZIxjapby0QVa1+iWYpEWfVVVcGxxT4F6uWfuqN3kSBJIJzfCTSXPp60zpCzvmDalYUUMn6Z3pjRAg/g8KXfhuEl4AYxXplH4GLHfMUTQUoopQvlmeyX1MLyJ9oBy0kPtz0qdcyNJ3FdKoGl4vdBod9S6GfosBVEpMgwSeodarZnWSrQbYOp4ZaAbsWnl99I7bHzU/h/rsYhFnr8+96oFQkA5HmAO+DbzbjQkaZuYlj3M9Z50/Z9wdDBCAh/Cm2+W/xeyVzd/HgThUP7uN/v3FWZd9nt9hO0mlkYQSSwOi8cvl+ybObF4uu6tD/faEn5Q/vyWwMk3WQKUq0atfDuDA9yshPPmJvDCmo6jmroh7HNsVuoSZLw7Q5JAh/1g1Eej6prALjnwPlA4GAQCInMwH3KgT/L7Xqfk1QDN0qWc509+FoFbltbIpEuQr4zWf8i8a1mPMlHwmw1Wh10qk3IP27qOyMNYyxEsYS2ElZxavY7d5vLfcNEwpDjKqL/i1jBCIfzIsN+jTG1fS8nO/q9Hcs8c1TFRyt5OL1X2Wc6ecdJQGTxoX74CKnRdViET8eUo1zaqRhCNu/aQ/bwFCKjF37EdjEcUpg9zQHXgQ809LRmo5eQF0qXcQ3voe4LqiJyHj/nAOmBRccH/0JG95IhWTggORQIwRXXqx1VY=
