language: python
branches:
  only:
  - master
install:
- pip install pelican
- pip install ghp-import
script:
- make publish github
env:
  global:
    - secure: q1PLHN65XTOcU2eaAbYk4FyvUMTr0r9AMHjztxs1b2o7HlUmxf5s8FTtlPkRj6/d66Lp2kFOm4p8Yfce0vT+sZfzy5RB+6KWKp2NN1k860oEvf8/z8qQlE02nWCDg1kM9KaK23P2QNZjqDfslMjZK2jQFlzUZj4XW51VPfiHgUNtYTjSos8sylPQr6NjTbrkV0ebqjjmk3ZinRDu0ekdfdVbLf1jzhJImO2WTlY28+3cK8YROdizZ2RwINRQGMqtAs+U/2aMm+y7bsShW1AilTp9yMiSB8Bqxx7T0kx8ewx1NqzygFaTjoQoR7+8a7wJ/FUCIdQzrUs1ejHOqYo86Muydl8pnpn4rPPeX0raODXdlM9vwhWtkDnXaMdk0W959w3+LpqU84LLvBbkJ6u0Oi/0HvGKGhHLf5Wn8ddV2pCX5GQMlYyWcOwCMYBWb9FdGZW8jnduKbch7L2wIJTuZvr7HDitPKCTmAxoGJTBmtzyLh/BT/9073SiaXnVGsKQhGwF6dxwxD6RAmWctYP4ecE+0Wi44AtyRCCaNeofUEvD2dIB5xbfo9V72R6jY1Fhys7IDj9aC63bQEjVr7plqNZjSysMxzOp9MAxqHR0zkjmnpMghWrgP0fYpe24t+fzCbOyJmB6Ye9Y9r5jD5mHpxlo2oFyxhRSEU5oapeHr8E=
