language: python
branches:
  only:
  - master
install:
- pip install pelican
- pip install ghp-import
- pip install pelican_gist
script:
- make publish github
env:
  global:
    - secure: D7GLayk9L49OmX8clZzRkrTQwmGZt3TsxKDBNf6JZFwOPksybVxi34TWoBUUVyBMQOdIP78kJkACnBvi9PyFxokWJp3Y0nPYczuJ87pp9nQ1JkRQU++91PWw/9scPC5nwIV1RkL4eaw6OHVLgPRx28aV2UjnV1pFHWQV6iL2a5SOHNctjPVvgVyeomV/N4Jki3G04p2FQo7tfxyzKkpC6ghJahYHdXH6jUkVx+8nslBVd8vCafg5eA60d+kIuFNsayZYzWS/rFH96xrDk0JCt8LJVcWR+W9aL6qR+wYPGviHr5/9MUyM7XvOBXOFukKejauFeFfnRrucX2t4RqxNUjNOqUl0GO3+2I8VwpRssksor6P9nZJAHblx3dZMpTcVUug2mKrE4DEjlL3s1ROzviIkdBgZ0qlE9VFzV7dAraGU7ozcAIunWyQkOELULxDvz6JwawMFQLg1qnF7IrM78/nRqXJN5Upgb2oSy1ZZn5NcNrfCNDbIGYcTlh3ef9bBPjqefYxM1ZFgVS+Kw7ZPV7IdVU7WKAe/puShdCMTJi6LVzZ1+vY3ts7wKriHryk+9mU42k7fs8NRM1q3nXuL198Ah4KLOcKAysXw/pc3xup2xNJHM9UdOp9+nQOAVio4wfxH4IVfKc883jGMt2QDlMv+wu15X/Nney1CRzJyHnM=
