language: python
branches:
  only:
  - master
install:
- pip install pelican
- pip install ghp-import
- pip install pelican_gist
script:
- make publish github
env:
  global:
  - secure: GkY75D+wAZRiMfdzgcQkeJKIvUQqwYyZezO6BXieMRoUaRO/9mVkWGuZwH3qiahcZke64dUm0ccUBSEky/r40HoRIeZPE72z53Rne6fST8PjRDwDJ8xNdYYJ4fuvTb+A1H7eeKPztxEZNdYzCcvkmLHEfPrIqLM/txcuVqyZe2OJgNJN1oZWVzTvPrbwtLQdu2YFL+KaWXho7Uo2pXlbNSGly8Y/rnUfsGJuI4sL5VKYcQS3QuJYSw+mMi3AphdJLKRAr3cri9YK8TWOODmqdNVC70qAD5PlJXz/1RzsDtl0p16/QF47ci3iwZ7bXSNqaF1wln45OKnliG3GanZ/cMQILz17G8KZfMz03MRqMXHvJyygsvmU2ycuyThbPNyBcmH40NsYYKMibV8pfYVMBgzMK+XCyFr9iP9d+REooylCc7es/4e4oAdyKBLCehmjeZw17YRQoWLPdiowYgykYfjqfOlAkhIu2NhePpSyLbzWrFnLiKqXHKyT93Qg/83n2rLN+DjZYnc33X+6kKlT5viucC58X+vixyeLukqR1h07bg4X1CdD3ENd066RpPnbFM82OMBZMjw0p3X7HrT4j1f1TFrqLzEj8o5felXD+VsgoPUlOM4ryeP+ZuVCfl1vJX4iv/C8mchpGvfWZGOzx/bCriGwqcH8ackfYp2Ch+Q=
  - secure: p4CQAL81QQIphy/pgz4Vr+WAxRmaaYXoVkkt40IkqVUAjP+qmVl2bgM2K8lDGB5dzOiV8FqAVr5noKpQdIndYQNjNBqq8KqaTehX1v2fjy6taI/opgxnQMboesOdDN7oU2Koxhkgv/NCCWvFMi3ogXf3x86nqCyFkIF6Tx8NIm1/3RIoslrqSbB3vAgc8VHb2iefZkmC3bjFlGk9ORjzOOShENgo8HQxF2iFj3RyLY+ood/vseN9dnI+BlIq9tPm1zAVHJnsaCCTE0JhNcDimPF7uuMNu9iwwVgvCO/uFbF3H7hHRWKaNjvctCJuz+RebEOzzquXdrlDCsoInje9h3voTQ8XE30n5CufbWIQmweoCifrzcIz0P2nS0VMW2AB4Meg/wkhJUwlwI428CiHi/h8eObjc1LixRtobz1D3ocQC5tcXFgfa92VM14ru98wKZ2eR7ANXG3duiapas3E50Py2nm+Js8/gVasTzW+aniTesocmcPLf6/If1ouJ1nJS3n0NejvGne04D4T8UjnKEkC2aIzVRN1Y0lFiDA7NLQp05aEDjj9Abh3lNBVozbUTSDZJ0z4nUMa+jE5lEThXUykHZ6ZYXU6UQtizbEniulA7EBhRHIx+FIbtwT7xmZLMbejd7KECrLjBczfT+mqKFM6pZk0fftLSTB060yJIBo=
